### ISSUE TITLE
Negative coordinated element

### ISSUE THREAD

**Issue by ubbn** [vvvv/SVG#174]
SVG elements on negative coordinated are not rendered. Existing code assumes no elements to be rendered on negative coordinates. And always renders coordinate (0,0) between (+,+). 

For example, below simple svg circle is rendered quarter circle. 
Wrong
![circle_wrong](https://cloud.githubusercontent.com/assets/1505531/8928936/0e8c2d18-3522-11e5-928f-f56b2a1848d1.png)
Correct 
![circle_correct](https://cloud.githubusercontent.com/assets/1505531/8928935/0e8abe56-3522-11e5-89fa-75b47de2d27d.png)

SVG code: 

<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
< svg version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
< defs>
	< symbol id="GeneratedGraphics" overflow="visible">
		< circle cx="0" cy="0" r="40" stroke="#000000" stroke-width="1" fill="none"/>
	< /symbol>
< /defs>
< use xlink:href="#GeneratedGraphics"/>
< /svg>

**Comment by carlosngis** [comment]
Hi ubbn,

On a similar subject...we are using this library to convert svg into png and print it on top of an arbitrary canvas/bitmap image

We've found that any elements outside the svg's viewbox are clipped out and not rendered entirely, even if we use  a larger canvas such as a Graphics object.

In a browser, we are able to control this by setting the overflow property of the svg class to be visible

svg
 {
  width:100%;
  height:100%;
  overflow: visible;
}

We have attached an image of such a scenario, showing the container div and the overflowing svg contents when renderer inside a browser.

Also attached, there's an image generated by converting the svg into png using this library
Is there any chance you can point us to where in the library's code we can modify this in order to allow overflowing contents (i.e. by passing a top-left corner point and letting the svg to be drawn freely anywhere inside a canvas and not necessarily from 0,0) ?

Thanks,

![svg using svgdll](https://cloud.githubusercontent.com/assets/16232365/11708222/f0e48b58-9f47-11e5-9fb5-688ee312edfa.png)
![visible div with overflow](https://cloud.githubusercontent.com/assets/16232365/11708223/f0ec0e82-9f47-11e5-9e09-907d9cc15c95.png)

**Comment by ubbn** [comment]
Hi,

Do simple test: Remove viewbox attribute, then this library will identify boundary of SVG itselft. Otherwise, it will always be to given viewbox. Also you can start yourself dive into, for example, SvgFragment.cs class where overflow property is declared and follow its usage and callers.

**Comment by carlosngis** [comment]
Hi ubbn,

Thanks for your help. Yes, stripping out the viewbox and setting svgDoc.Overflow = SvgOverflow.Visible did the trick for us.

Before having the svg contents rendered on the empty Graphics object, we use the original viewbox and geographic bounds (the ones that match the non-overflowing content) to get the exact scale and translation values, this forces the svg content to match the background imagery (See attached image )

Thanks again !!

![overflowing](https://cloud.githubusercontent.com/assets/16232365/11830814/693c63ba-a3e3-11e5-8336-d9a1854578f0.png)

**Comment by ubbn** [comment]
Good luck! Looks interesting project.
