### ISSUE TITLE
Invalid Property Value working with Scale Transform with 0 x or y

### ISSUE THREAD

**Issue by granth5** [vvvv/SVG#196]
Working with the SVG component, when processing a scale() attribute, if either the X or Y coordinate is 0, getting an "invalid property value" when SvgElement.cs::PushTransform() attempts to update the renderer.Transform after doing the matrix multiplications.

I've coded around by ignoring the scale() if either X or Y is 0, but since i see examples of using this syntax, wondering if anyone else has dealt with this?  Maybe there's a setting / property?  Can't tell since there's no documentation.

**Comment by mrbean-bremen** [comment]
As far as I undestand, a scale parameter of zero is invalid, so the behavior is somewhat expected.
If this is something that happens in valid SVGs (or SVGs created with common tools) we shall add some workaround (setting it to 1?), otherwise I don't see this as a bug.
Closing - please reopen, if this is still an issue.
