### ISSUE TITLE
Can I use this on a UWP Win 10 App?

### ISSUE THREAD

**Issue by JohnTortugo** [vvvv/SVG#219]
When I add the lib to my project using Nuget and try to recompile the project I get this error:

2>C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets(350,5): Xaml Internal Error error WMC9999: Cannot find type System.MarshalByRefObject in module CommonLanguageRuntimeLibrary.

**Comment by mihailostojanovic** [comment]
I cannot get it to work on UWP, after seemingly successful  install from nuget, I can not reference the library, getting this error : "This project cannot be viewed in the object browser because it is unavailable or not yet built". Please can you confirm it is not yet  ready for UWP apps? Or if there is a solution to this? Thanks, Mihailo

**Comment by jonthysell** [comment]
SVG.NET requires the System.Drawing namespace, which is not available in UWP. See http://stackoverflow.com/questions/31545389/windows-universal-app-with-system-drawing-and-possible-alternative

**Comment by mrbean-bremen** [comment]
Closing as answered.
