### ISSUE TITLE
the drawing text problems in 2.2.1

### ISSUE THREAD

**Issue by Steven0621** [vvvv/SVG#237]
When I use the latest version to create an image, 
the text on the image is very blurred,why?
![20160530133807](https://cloud.githubusercontent.com/assets/6915294/15640555/d0d5a38c-266b-11e6-8e13-c1caee55a4a1.png)

**Comment by tebjan** [comment]
hi, was it different before? which version was working good for you?

**Comment by heindla** [comment]
I think this is a problem during the anti-aliasing of the text, it seems that is takes always the background as transparent instead of the color of the underlying graphic. I have the same problem, but I only started using it from version 2.2.0 and have no experience of versions before.
![1440](https://cloud.githubusercontent.com/assets/19708102/15743528/7c4c3706-28c6-11e6-996c-9bebe123a32c.png)

**Comment by heindla** [comment]
I tested it now with 2.1.0. here it works, so the issue is between 2.1.0 and 2.2.0.
![1443](https://cloud.githubusercontent.com/assets/19708102/15744146/95354f24-28ca-11e6-8566-4fb86febf7f8.png)

**Comment by tebjan** [comment]
thanks for checking!

**Comment by tebjan** [comment]
could you also provide svg test files? thank you!

**Comment by heindla** [comment]
sure, you're welcome.

It github did not accept my svg or zip so I attached it as txt ...

[TestFile_Text_over_Shape.txt](https://github.com/vvvv/SVG/files/297509/TestFile_Text_over_Shape.txt)

**Comment by tebjan** [comment]
please try with latest nuget 2.3.0, there was a problem with text rendering that might now be fixed.

**Comment by mrbean-bremen** [comment]
Looks good with current version - closing.

**Comment by heindla** [comment]
Yes, this works. Thanks
