### ISSUE TITLE
SvgDocument Width and Height doesn't work

### ISSUE THREAD

**Issue by askeet** [vvvv/SVG#246]
I used prev version from https://svg.codeplex.com/ and when I changed property Width and Height of  SvgDocument my svg file is scaled. 
But when updated library to  https://github.com/vvvv/SVG/ it doesn't work.

_svgDoc = SvgDocument.Open(pathToFile);
_svgDoc.Width = new SvgUnit(SvgUnitType.Pixel, _target.Width);
_svgDoc.Height = new SvgUnit(SvgUnitType.Pixel, _target.Height); 
_svgDoc.Draw();

How can I transform SVG file?

I want to scale Document **without preserving the proportions**

**Comment by Alko89** [comment]
I want to do the same thing. I'm trying to include a svg file into another one and the image gets cropped instead of scaled.
This is the image:
![palete](https://user-images.githubusercontent.com/2822030/33126268-312ade42-cf84-11e7-809e-d990be160294.png)
And this is what I get if I put two of them in another image:
![paletenalozenebug](https://user-images.githubusercontent.com/2822030/33126298-47217a58-cf84-11e7-9bfc-46021b609aa2.png)

**Comment by mrbean-bremen** [comment]
There is an overload to SvgDocument.Draw() that takes a width and a height. If both are given, the aspect ration is ignored.

**Comment by mrbean-bremen** [comment]
Added to [Q&A](https://github.com/vvvv/SVG/wiki/Q&A#how-to-render-an-svg-document-to-a-bitmap-in-another-size), closing.
