### ISSUE TITLE
Polygon not rendered if "stroke-width" = 0

### ISSUE THREAD

**Issue by RaeuberHotzenplotz** [vvvv/SVG#256]
The following svg renders correctly in my browser, but produces nothing in this library. There seems to be a problem when the stroke-width is explicitly set to 0.

<svg id="svg2" version="1.1" preserveAspectRatio="xMidYMid meet" viewBox="0 0 200 200">
  <polygon fill="Red" stroke="Black" stroke-width="0" points="0,0 200,0 0,200 200,200" />
</svg>

**Comment by leviathan25** [comment]
I have encountered the same issue. I cannot tell when reading the documentation on SVGs whether or not this is intentional. The SVG documentation just says the line will not be rendered, but it doesn't say that the entire object will not be rendered. If I view the same SVG in a browser, the elements still render (without lines) so I assume it's a bug.
