### ISSUE TITLE
Set SvgUnit DPI

### ISSUE THREAD

**Issue by KieranSmartMP** [vvvv/SVG#313]
Hi, I am having trouble rendering my SVG using Batik as I am trying to render at a higher dpi than the default 96dpi.

There would appear to be no clear way of allowing me to override the default DPI for any or all measurements in an SvgDocument.

At the moment I am now avoiding the use of SvgUnit and I am calculating everything myself, which is a pain and I would much rather use the SvgUnit class

Thanks

**Comment by n4idaham** [comment]
Did you ever get this problem resolved? I'm dealing with the same problem.

Thanks Al

**Comment by mrbean-bremen** [comment]
There has been a change recently that takes the DPI from the system settings instead of using the hard-coded value, though this would probably not solve your issue, if I understand that correctly.
Though it should be easy to add a possibility to overwrite the system DPI, if needed. Is that what you need (in case this is still an issue)?

**Comment by mrbean-bremen** [comment]
Actually, `SvgUnit` takes the DPI (which is called `Ppi` here) from the document. This is set to the system DPI at creation time, but can be set to another value afterwards, e.g. 
```c#
  doc = SvgDocument();
  doc.Ppi = 200;
  ...
```

**Comment by mrbean-bremen** [comment]
Added to [Q&A](https://github.com/vvvv/SVG/wiki/Q&A#how-to-change-the-svgunit-dpi), closing.
