### ISSUE TITLE
Text does not render

### ISSUE THREAD

**Issue by centDejan** [vvvv/SVG#318]
I have created SVG document with the FacbricJS (please find file attached).
However when I would like to render it, it does not render texts inside the file.
Text is shown if file is opened with Inkscape or any other SVG editor...

			var svgText = System.IO.File.ReadAllText("f:\\temp\\s1.svg");
			var svg = Svg.SvgDocument.FromSvg<Svg.SvgDocument>(svgText);
			var bmp = svg.Draw();
			pictureBox1.Image = bmp;

It there any workaround here?
Would appreciate quick response.

[s1.zip](https://github.com/vvvv/SVG/files/995470/s1.zip)

**Comment by smallBlacks** [comment]
i have no idea,please tell me

**Comment by haykpetros** [comment]
Hi @centDejan,

If you look closer to your `tspan` elements you will notice that `style` attribute contains `fill-rule` CSS declaration that has no value. So that is causing parser to fail and not to render rest of your document. Here is an example from your document:

`<tspan x="-62.26" y="10.08" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: ; opacity: 1;">T</tspan>`

So if you either remove `fill-rule` declaration completely or add any value to it, for example `nonzero` it will render just fine. Here is example that will render:

`<tspan x="-62.26" y="10.08" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;">T</tspan>`

Attached is updated document that will work for you.

Now what is related to the library itself problem is with `public StyleSheet Parse(string css)` method in `External\ExCSS\Parser.css` (see line 64) that is not handling this situation properly, because generally speaking this is a properly formed CSS. So that causes exception and prevents document from rendering rest of the document, but actually it should assume a default value for the declaration when no value is specified.

I am not an expert with parsers, but hopefully someone who is will pick form here and address this very common problem.

Thanks

[s1 - FIXED.zip](https://github.com/vvvv/SVG/files/1219837/s1.-.FIXED.zip)

**Comment by centDejan** [comment]
Dear @haykpetros!

Thank you for taking your time to locate the root of the issue. You did
amaizing job!

Dejan

**Comment by haykpetros** [comment]
Hi @centDejan,
 
Happy to help you and contribute to this great library!

Thanks
