### ISSUE TITLE
netstandard compatibility

### ISSUE THREAD

**Issue by MaitreDede** [vvvv/SVG#346]
Hi,
Is it possible to refactor SVG a bit so core SVG parsing is compatible with `netstandard`, and rendering is split into other libraries ? So there can be an implementation for the `framework` (the actual one), and implementations for dotnet core (based on [ImageSharp](http://imagesharp.net/) for example).
Thanks.

**Comment by tebjan** [comment]
hello @MaitreDede, the library is open source. you are welcome do refactor it to your liking. if got something running, don't hesitate to open a pull request.

**Comment by wyshmily** [comment]
@MaitreDede do you have a solution now?

**Comment by MaitreDede** [comment]
@wyshmily The solution would be to fork and refactor. 

The `System.Drawing` library is deeply integrated inside `SVG`, so does `System.Web`. Removing dependencies on both needs to rethink the library.

This will be really time-consuming.

**Comment by mmosca** [comment]
It may be possible to still depend on System.Drawing basic types and
refactor the rendering itself to use something else.

.Net Core does have a lot of the types in System.Drawing available, just
not the GDI rendering code.

**Comment by MaitreDede** [comment]
The Gdi rendering part is in preview. I think it should be better to split
SVG handling and rendering to allow custom rendering engines.
For example I would be pleased to have a rendering based on ImageSharp.

Le 22 nov. 2017 19:24, "Marcelo Bezerra" <notifications@github.com> a
écrit :

**Comment by JimBobSquarePants** [comment]
Having had a quick look at the library it would take serious refactoring to allow enough abstraction to use another rendering engine like ImageSharp since the integration is so [tightly coupled](https://github.com/vvvv/SVG/blob/7ce4de6297dbd6be898de5bc7cb6ca5cb9cd2090/Source/SvgDocument.cs#L426).

Since System.Drawing will never be part of the NetStandard and is being worked on now as part of the [Windows Compatibility Pack](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/) to help with migrations only I would recommend making such an abstraction a priority if NetStandard support is a goal for the library.

**Comment by JaedsonBarbosa** [comment]
Hi, I'll try to port that for the .NET Standard, but that port won't have the renderer system, it just will generate the SVG files using a black and white image.

**Comment by wieslawsoltes** [comment]
To make it compatible with `netstandard2.0` [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) can be used.

**Comment by tub5** [comment]
> To make it compatible with `netstandard2.0` [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) can be used.

Please note this is not ideal on Linux due to System.Drawing.Common [not being properly supported](https://github.com/dotnet/runtime/issues/53663)

**Comment by mrbean-bremen** [comment]
@wieslawsoltes, @gvheertum: any thoughts on this?
