### ISSUE TITLE
SVG to Icon

### ISSUE THREAD

**Issue by spreedated** [vvvv/SVG#376]
I'm trying to create an Icon out of a SvgDocument, currently I'm using drawing to Bitmap and from there to Icon by getting the HIcon, however the result isn't good at all, especially at small size icons like TrayIcons (16x16). Is there a way to draw/render directly to an Icon?

My approach so far was to create an Icon from Byte() MemoryStream, but I get a System.ArgumentException doing so.

`Dim tagArray As Byte() = My.Resources.temperature_high 'SVG from resource

Dim msAs System.IO.Stream = New System.IO.MemoryStream(tagArray)

Dim thisIcon As System.Drawing.Icon = New System.Drawing.Icon(ms)`

I'm currently working on a VB app, but C# code is fine too.

**Comment by mrbean-bremen** [comment]
I think your approach to create a bitmap of the correct size and the icon from that bitmap is the correct one. Creating the icon directly from the svg won't work, because the argument is expected to be a picture, not an xml string as in the case of the SVG.
So your problem with the bad quality is not related to the icon, just to the small size - maybe the SVG is just not suited for that purpose, or maybe there is some rendering bug.

**Comment by mrbean-bremen** [comment]
I'm closing this as answered - please file a new issue if you have a problem with a specific svg that is rendered incorrectly.
