### ISSUE TITLE
Attached svg does not render in SVGViewer

### ISSUE THREAD

**Issue by raelb** [vvvv/SVG#398]
[test2.zip](https://github.com/vvvv/SVG/files/2730345/test2.zip)

It should look like this:

![image](https://user-images.githubusercontent.com/13108198/50734763-b0d05080-11ac-11e9-92d7-1e1794fb2db1.png)

**Comment by mrbean-bremen** [comment]
Ok, I played around with the SVG, and the problem is `fill="currentColor"`. As there is no color defined, the fill color shall be set to the default (which is black), but for some reason is set to `none` (which is the bug as far as I can see). Removing `fill="currentColor"` fixes the problem in the SVG.
