### ISSUE TITLE
Modify SVG file to include width and height of graphic in SVG tag

### ISSUE THREAD

**Issue by halilozanyilmaz** [vvvv/SVG#421]
I've a lot of SVG files (several graphics like, dogs, trees, birds, buildings etc.), and they are from different sources from web. I need to define height and width of these SVGs.

Example: 

```
<svg id="svg1" viewBox="0 0 36 33" xmlns="http://www.w3.org/2000/svg">
 <path d="m18 0.0938-17.719 16.281h5.5625v15.531h24.312v-15.531h5.5625l-17.719-16.281z"/>
</svg>
```
I need to modified the file with as below: 

```
<svg width="630" height="577" viewBox="0 0 36 33" xmlns="http://www.w3.org/2000/svg">
 <path d="m18 0.0938-17.719 16.281h5.5625v15.531h24.312v-15.531h5.5625l-17.719-16.281z"/>
</svg>
```

1- How can I get width and height of the graphic ? (Ratio is enough) Normally in javascript, I can find the width and height as below.

```
var svg1 = document.getElementById('svg1');
console.log('client', svg1.clientWidth + 'x' + svg1.clientHeight);
```

2- How can add these attributes to svg tag.

**Comment by mrbean-bremen** [comment]
> How can I get width and height of the graphic ?

There is usually no such thing in an SVG, except it is already set in the svg tag - this is basically the point of vector graphics.

> How can add these attributes to svg tag.

I propose you just set the values you need using any xml/dom framework. The "preserveAspectRatio" property is by default set to "xMidYMid", which is probably what you want - otherwise you can set it, too.
As far as I can see, you don't need SVG.NET to accomplish this, but maybe you need it to do something else - depends on your use case.

**Comment by mrbean-bremen** [comment]
Closing as answered.
