### ISSUE TITLE
Problem with Round cap and dash-strokearray

### ISSUE THREAD

**Issue by MichaelBjerregaard** [vvvv/SVG#508]
#### Description
In the attached SVG the dasharray (1.40 , 1.00) first becomes (0.56, 0.40) in SVGVisualElement line 291.
When adjusting for round cap, it becomes (1.56, -0.59) which is invalid.

Changing line 303 to 
      pattern[i] = Math.Abs(pen.DashPattern[i] + offset);  
will avoid the exception, but will probably not paint a correct dash.

#### Example data

[SVG1155.svg.txt](https://github.com/vvvv/SVG/files/3368658/SVG1155.svg.txt)

[DashArrayTests.cs.txt](https://github.com/vvvv/SVG/files/3368665/DashArrayTests.cs.txt)

#### Used Versions
master branch

**Comment by mrbean-bremen** [comment]
Hm, I see the problem - this basically happens if the caps overlap. Using `Abs` may not be the best solution, as that would widen the gap. As GDI is not able to draw an overlapped dashed line (at least not directly), we either have to decompose the dash and draw each part separately (cumbersome and probably not worth it, given that overlapping dashes are not exactly a widely used feature), setting the gap size to a very small value (this would make the gaps wider to not have overlap), or not use a dash at all in this case. Any thoughts?

**Comment by MichaelBjerregaard** [comment]
I can see in #191 what you wanted to achieve, and in my opinion there is no need to make a lot of work out of it.
It seems that a large stroke-width combined with relatively small dash/gap values can create the negative values. In my case a stroke-width of 2.5 and a dash/gap of 1.4/1, which will turn into a solid line if properly adjusted for round caps.
I will suggest that if the average width of dash + gap is less than 2 * stroke-width then ignore round caps.

**Comment by mrbean-bremen** [comment]
Agreed - thanks. I will see if can do this tonight.

**Comment by mrbean-bremen** [comment]
@MichaelBjerregaard - you can have a look at the PR. I added your test to make sure your example doesn't crash, and a simpler example (shown in the PR) to check the functionality.

**Comment by MichaelBjerregaard** [comment]
Thank you for acting so swift.
It looks good.


Fra: mrbean-bremen <notifications@github.com>
Sendt: 10. juli 2019 21:04
Til: vvvv/SVG <SVG@noreply.github.com>
Cc: Michael Bjerregaard <mbp@rib-software.dk>; Mention <mention@noreply.github.com>
Emne: Re: [vvvv/SVG] Problem with Round cap and dash-strokearray (#508)


@MichaelBjerregaard<https://github.com/MichaelBjerregaard> - you can have a look at the PR. I added your test to make sure your example doesn't crash, and a simpler example (shown in the PR) to check the functionality.
