### ISSUE TITLE
Developer chat

### ISSUE THREAD

**Issue by tebjan** [vvvv/SVG#589]
I guess most of us get quite a few emails from github every day and it's easy to miss things. so i thought it could make sense to create a chat room for the repository. we at vvvv are using matrix.org, but i guess gitter or something similar would be fine too. what are your thoughts about that, what do you use regularly?

**Comment by mrbean-bremen** [comment]
I have no preference here. We use gitter in one project, and just private mail in another where are basically only two of us, but I'm fine with other means.

**Comment by mrbean-bremen** [comment]
But I agree that it's really a good idea to have some other communication medium than issues and PRs - I also have the problem that I miss messages, or my messages are missed...

**Comment by gvheertum** [comment]
I agree. Missing messages/issues/etc is also a thing for me. I tried manually checking the repo every once in a while, but sometimes I completely forget about github all together :)

For quick catching up or small discussions I think a chat might work. Although since this is for most contributors kind of a hobby, the chat might be somewhat of a "slow-chat", but I guess that's okay.

**Comment by mrbean-bremen** [comment]
Over at pydicom we actually use 2 chats in gitter - one open for anyone to join and chat, and one private for core developers only (mainly for admin stuff). The caveat is of course, that you also can miss gitter notifications... but then you just may check the chat periodically.
Slow-chat is inevitable due to different time zones and availabilty, but that is something we have to live with.

**Comment by tebjan** [comment]
made a public one, lets see who joins: https://gitter.im/vvvv/SVG
