### ISSUE TITLE
Fizzler (1.1.0) warning when installing svg.core nuget on .net standard 2.0 project

### ISSUE THREAD

**Issue by ChristinaFaur** [vvvv/SVG#716]
![image](https://user-images.githubusercontent.com/63300027/79722202-ec305900-82e3-11ea-86ba-9d5bd8efc445.png)

**Comment by H1Gdev** [comment]
@ChristinaFaur 

Please use [Svg](https://www.nuget.org/packages/svg).

@mrbean-bremen 

What is [Svg.Core](https://www.nuget.org/packages/Svg.Core/) ??

**Comment by mrbean-bremen** [comment]
> What is Svg.Core ?? (#595 ?)

Never saw that - seems to be a copy of SVG. Looks like you are right regarding that PR - most certainly taken from [here](https://github.com/mccj/SVG/commits/master), which is an older release with the PR added.
A bit unfortunate regarding the naming - this was actually a name we have been considering for the moved repo (or does it already exist?). For some reason he decided to register an own NuGet instead of answering the questions in the PR...
Also completely misleading, as he did not add any additional description, so it looks like SVG.

**Comment by mrbean-bremen** [comment]
Closing as not related to this project.
